<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pig</string>
		<string>piglet</string>
	</array>
	<key>name</key>
	<string>Pig</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
                        <string>\b(?i:all|and|as|asc|by|cube|cogroup|cross|debug|default_parallel|define|dense|desc|describe|distinct|dump|explain|filter|flatten|foreach|generate|group|if|illustrate|inner|into|is|job.name|join|limit|load|mapreduce|matches|not|null|or|order|outer|parallel|rank|register|sample|set|split|store|stream|stream.skippath|through|union|using)\b</string>
			<key>name</key>
			<string>keyword.operator.pig</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>--</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.double-dash.pig</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.pig</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.pig</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\$)[a-zA-Z]([a-zA-Z0-9_]*)</string>
					<key>name</key>
					<string>variable.other.pig</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(\$)[a-zA-Z]([a-zA-Z0-9_]*)</string>
			<key>name</key>
			<string>variable.other.pig</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\$)[0-9]+</string>
			<key>name</key>
			<string>variable.language.pig</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(bag|bytearray|boolean|chararray|datetime|double|float|int|long|map|tuple)\b</string>
			<key>name</key>
			<string>constant.language.pig</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(%declare|%default)\s</string>
			<key>name</key>
			<string>keyword.control.import.pig</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|F|f)?\b</string>
			<key>name</key>
			<string>constant.numeric.pig</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.pig</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([a-zA-Z0-9_\.]*?)\(</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pig</string>
	<key>uuid</key>
	<string>EF1825E8-6B1C-11D9-B883-000D93589AF6</string>
</dict>
</plist>
